### ISSUE TITLE
Still interested in maintaining this?

### ISSUE THREAD

**Issue by ndarilek** [darbaga/Tolk-rs#2]
Hello,

I'm a blind Rust developer interested in contributing to this project. I'm using Tolk primarily for game development of audio games. Most recently, I'm trying to use it with [godot-tts](https://gitlab.com/lightsoutgames/godot-tts) which in turn is used by my [godot-accessibility](https://gitlab.com/lightsoutgames/godot-accessibility) plugin for the [Godot game engine](https://godotengine.org).

I realize this is a simple library, but I'd like to make it a bit easier to work with. I'd be interested in co-maintaining or taking over ownership completely--either way. I'd rather not fork the library if I can avoid it, but I'll probably need to in order to do some of the work I'd like.

Thanks.

**Comment by darbaga** [comment]
Hey.

Honestly, this was just a really rough project I threw together because I wanted to play with small Rust game stuff. I didn't expect it to really get noticed :)

I'd definitely be willing to transfer ownership. I haven't really had the time to do Rust-related things recently (and that won't change for quite a while) so co-maintenance really doesn't make sense.

Transferring repositories is easy..The difficult bit will be transferring ownership on the crates.io registry. I don't see any way to do that. I could intermittently publish new versions as you develop them, though this is suboptimal..probably what you'd want to do is publish the crates under a different name and link people to them.

Anyway, get back to me with your agreement and I'll transfer over the repos.

**Comment by ndarilek** [comment]
Cool, intermittent publishing wouldn't be a bad approach IMO. I don't 
imagine the burden will be too great for you since the library is fairly 
small, and I don't imagine making many changes. Thus far I'm thinking:


  * My PR made speech interruption a bit clearer, since using method 
names was a bit opaque.

  * It's recommended to either link against an installed library, or to 
compile vendored sources as part of a sys crate. I'd like to vendor a 
recent Tolk version and build it in the sys crate's build.rs, so instead 
of copying libraries around, the correct library for a given target is 
compiled alongside dependent crates and installed into target/. I have 
some experience doing this with 
[spatialite-sys](https://gitlab.com/ndarilek/spatialite-sys), which 
compared to Tolk is a bit of a monster. :) I imagine Tolk doesn't change 
very often, so it's probably safe to vendor a recent version.


Anyhow, I probably won't be interested in taking a stab at any of this 
for a few weeks, but I wanted to check if you were still interested in 
maintaining this project, because I definitely need it. :)
